### ISSUE TITLE
run and debug does nothing?

### ISSUE THREAD

**Issue by mkarikom** [julia-vscode/docs#32] opened 2021-03-09 16:36 UTC
Not sure why this just started happening, but hitting "Run and Debug" doesn't do anything, no errors or other messages.  How can I diagnose this?  Thanks

**Comment by davidanthoff** [comment] 2021-03-09 16:56
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/2003.

**Closed by davidanthoff** 2021-03-09 16:56 UTC
